version: "3.9"
services:
  postgres-database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./python-server:/app
      - ./angular-app/dist/angular-app:/angular-app
    depends_on:
      - postgres-database
    restart: always
    command: nodemon -L --watch /app --ext py --exec "python server.py"



