version: "3.9"
services:
  postgres-database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgres-data:/var/lib/postgresql/data
    restart: always


  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./python-server:/app
      - ./resources/uploads:/app/uploads
      - ./resources/text_to_speech:/app/text_to_speech
    depends_on:
      - postgres-database
    command: nodemon -L --watch /app --ext py --exec "python server.py"

  angular-build:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./resources/dist:/app/dist

  angular-serve:
    build:
      context: ./angular-app
      dockerfile: Dockerfile_serve
    env_file:
      - .env
    ports:
      - 4200:4200
    volumes:
      - ./angular-app:/app/
      - ./angular-app/src:/app/src

